# Generated by Django 5.0.4 on 2024-11-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='picture',
        ),
        migrations.AddField(
            model_name='customersos',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
