# Generated by Django 5.0.4 on 2025-03-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customer_picture_customersos_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlocation',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
