# Generated by Django 5.0.4 on 2025-12-16 19:47

import django.db.models.deletion
from django.db import migrations, models


def create_default_company_and_assign_customers(apps, schema_editor):
    Company = apps.get_model('core', 'Company')
    Customer = apps.get_model('core', 'Customer')

    default_company, created = Company.objects.get_or_create(
        name="Default Company",
        defaults={
            'address': 'N/A',
            'phone': 'N/A',
            'email': 'default@example.com',
            'NIT': 'N/A'
        }
    )

    # Update all existing Customer instances to set their new company_id field
    # For this to work, Customer should have the new `company_temp_id` field
    # We will assume that `company_temp_id` will be added in a previous step of this migration.
    for customer in Customer.objects.all():
        customer.company_temp = default_company
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customerlocation_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('NIT', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        # 1. Add a temporary ForeignKey field (company_temp) to Customer
        migrations.AddField(
            model_name='customer',
            name='company_temp',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.company',
                null=True,
                blank=True,
                default=None # Important: Make it nullable initially
            ),
        ),
        # 2. Run Python code to create default company and assign it to existing customers
        migrations.RunPython(create_default_company_and_assign_customers, migrations.RunPython.noop),
        # 3. Remove the old CharField 'company'
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        # 4. Rename 'company_temp' to 'company'
        migrations.RenameField(
            model_name='customer',
            old_name='company_temp',
            new_name='company',
        ),
        # 5. Alter the new 'company' field to remove default=None if desired,
        #    or keep it if it's meant to be optional from now on.
        #    Since it's null=True, blank=True in models.py, we don't need to change it here.
    ]
