/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Calculated: typeof import('./src/components/expInput/calculated.vue')['default']
    DateTime: typeof import('./src/components/expInput/dateTime.vue')['default']
    ExpCrop: typeof import('./src/components/expCrop/expCrop.vue')['default']
    ExpModalForm: typeof import('./src/components/expModalForm/expModalForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputDelay: typeof import('./src/components/expInput/inputDelay.vue')['default']
    MaskNumber: typeof import('./src/components/expInput/maskNumber.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
